### ISSUE TITLE
Add how much libraries remaing in .sh files

### ISSUE THREAD

**Issue by TomasRoj** [per1234/inolibbuglist#9]
Hey,

When I am making pull requests and running the .sh file, it would be good to print have more links it will open every time I close the actual one. This lets me plan how much time I will need.

**Comment by per1234** [comment]
I don't understand the request. Please provide a detailed description of your proposal.

**Comment by TomasRoj** [comment]
When I open sh file I make pull request and then I Close the Firefox. Script automatically opens Firefox again but with different link. I want if it's able to print how many times it will open the Firefox window (how many is left).

**Comment by per1234** [comment]
I understand now. Thanks.

On my computer the browser script loads all the repositories in tabs all at the same time when I run the script. I actually prefer that behavior because I do the PRs for some bugs in assembly line fashion. By that, I mean my workflow is like this:
1. Run a browser script. 35 tabs are opened in my browser. I set each script to contain a maximum of 35 repositories because this was about the most tabs I can have opened without risking slowing/glitching/or crashing my browser.
2. Check for pre-existing pull requests for the bug in all 35 tabs.
3. Fork all 35 repositories
4. Go through whatever the process is to fix the bug, doing each step 35 times before moving on to the next step (the process differs from one bug to another).
5. Commit and push fixes to all 35 forks.
6. Submit pull requests to all 35 repositories

Often this assembly line approach is much more efficient than going through the entire process one repository at a time. In other cases, it's probably better to do it one at a time. I could see your codespell project working best with the one-at-a-time approach, though I'm not sure because I never worked on that particular bug before.

I feel like this behavior of the script is caused by the `-new-tab` option it uses not working. Which browser are you using?

Do you like how the script is currently behaving for you, or would you prefer it to open all 35 repositories at once in tabs in your browser (as I intended it to work)?

**Comment by TomasRoj** [comment]
Hey. I am using Firefox. I think I found by best workflow and I already make maybe 50 pull requests. So idk it depends on you. I prefer this type so workflow so it will be good for me.

**Comment by TomasRoj** [comment]
So whats the status of this request?

**Comment by per1234** [comment]
I'll do it before the next time I run the script for you.

**Comment by TomasRoj** [comment]
Ok thanks
